### PR TITLE
Add Raid/Heroic inflection points

### PR DESCRIPTION
**Pull request by Darkon47**
Adds to the code and config inflection points for Heroics, 10 man raids, 25 man raids, other raids, Heroic 10 man raids, heroic 25 man raids, and other heroic raids.

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@bogir

**Comment by Bogir** [comment]
Compiled fine)
But how to test it? What difference must I see?

**Comment by Yehonal** [comment]
This PR must be improved. The condition can be simplified and be more
flexible. For example, what about if someone would like a different
inflection point per instance instead of per type?

The solution would be to let the user to select its preferred condition
instead of giving a fixed list of configuration with a bad-written if-else
block.

**Comment by BarbzYHOOL** [comment]
Ok yehonal but what about merging this first as it's already an improvement, and work on a newer PR after that?

**Comment by Yehonal** [comment]
The new PR will eventually deprecate those configurations. I prefer to not merging it for now. I'll think about an alternative that can be used to other cases too, asap. 

Meanwhile, if someone need it you can just run git pull https://github.com/Darkon47/mod-autobalance.git patch-2

**Comment by Stoabrogga** [comment]
Pushed a commit to improve the readability of the if-else block. Why can't we just merge this?
In my opinion:
- the implementation is simple and can be easily reverted if necessary
- it is downwards compatible
- it provides additional flexibility
- the users can use it now instead of having to wait for several weeks (or months?)

Also I think that this amount of flexibility suffices, you have to weigh flexibility vs usability. Too many configuration options are only confusing people, especially if those options are not really necessary.

**Comment by Stoabrogga** [comment]
Merging this. @Yehonal like I wrote above, the changes are simple and can be reverted easily if necessary.

**Pull request merged**
