### PR TITLE
fix: Include new parameter for OnGiveXP hook.

### PR DESCRIPTION
**Pull request by AnchyDev**
### Description
Includes the new XPSource parameter for the OnGiveXP hook.

This PR should only be merged when the core PR is merged.

### Issues
https://github.com/azerothcore/azerothcore-wotlk/pull/16109

### Testing
No testing needed really, just a signature change.

### CODE REVIEW

**Comment by Helias** [comment]
build is failing
```
/home/runner/work/mod-autobalance/mod-autobalance/modules/mod-autobalance/src/AutoBalance.cpp:373:89: fatal error: non-virtual member function marked 'override' hides virtual member function
        void OnGiveXP(Player* player, uint32& amount, Unit* victim, uint8 /*xpSource*/) override
                                                                                        ^
/home/runner/work/mod-autobalance/mod-autobalance/src/server/game/Scripting/ScriptMgr.h:1038:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (3 vs 4)
    virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/) { }
                 ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-autobalance/src/AutoBalance.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1199: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by AnchyDev** [comment]
> build is failing
> 
> ```
> /home/runner/work/mod-autobalance/mod-autobalance/modules/mod-autobalance/src/AutoBalance.cpp:373:89: fatal error: non-virtual member function marked 'override' hides virtual member function
>         void OnGiveXP(Player* player, uint32& amount, Unit* victim, uint8 /*xpSource*/) override
>                                                                                         ^
> /home/runner/work/mod-autobalance/mod-autobalance/src/server/game/Scripting/ScriptMgr.h:1038:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (3 vs 4)
>     virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/) { }
>                  ^
> 1 error generated.
> make[2]: *** [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-autobalance/src/AutoBalance.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1199: modules/CMakeFiles/modules.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

I am just waiting on the core PR to be reviewed and merged, I made this PR for when that happens. :smile:

**Comment by Helias** [comment]
oh sorry, perfect, ping me when we can merge this PR
you can write a comment here, I will receive a notificationo

**Comment by AnchyDev** [comment]
> oh sorry, perfect, ping me when we can merge this PR you can write a comment here, I will receive a notification

It has been merged.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
